server:
  port: 8086

feign:
  okhttp:
    enabled: true # 开启OKHttp功能

hm:
  db:
    database: hm-pay
  swagger:
    title: "黑马商城支付接口文档"
    package: com.hmall.pay.controller

spring:
  rabbitmq:
    host: 192.168.223.100 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123456 # 密码