server:
  port: 8085

feign:
  okhttp:
    enabled: true # 开启OKHttp功能

hm:
  db:
    database: hm-trade
  swagger:
    title: "黑马商城交易接口文档"
    package: com.hmall.trade.controller

spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.223.100:8090
      http-method-specify: true # 开启请求方式前缀