server:
  port: 8081

feign:
  okhttp:
    enabled: true # 开启OKHttp功能

hm:
  db:
    database: hm-item
  swagger:
    title: "黑马商城商品接口文档"
    package: com.hmall.item.controller

spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.223.100:8090
      http-method-specify: true # 开启请求方式前缀

