server:
  port: 8082
feign:
  okhttp:
    enabled: true # 开启OKHttp功能

hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商城购物车接口文档"
    package: com.hmall.cart.controller

spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.223.100:8090
      http-method-specify: true # 开启请求方式前缀
  rabbitmq:
    host: 192.168.223.100 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123456 # 密码